language: python
python:
  - 3.6

install:
  - pip install robotframework

script:
  - python setup.py test
  - robot ./test_cases/hello.robot

notifications:
  slack: tuntunkun:puqmjBAZ8WDYrMN1HaKNrmHd

