"""empty message

Revision ID: 53c783681e06
Revises: 62987f8d47fa
Create Date: 2018-11-16 23:21:24.390797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53c783681e06'
down_revision = '62987f8d47fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('M_ACCOUNT', sa.Column('LOCK', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('M_ACCOUNT', 'LOCK')
    # ### end Alembic commands ###
